name: Build release

on:
  release:
    types: published

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: 'pypy3.9'

      - name: Install meson and ninja
        run: pip install -r requirements.txt

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: Configure
        run: meson setup bin --buildtype release

      - name: Compile
        run: meson compile -C bin

      - name: Create zip
        working-directory: out
        run: 7z a "../cem-tool-${{ github.ref_name }}.zip" "cem_tool.exe" "mmfs2.dll"

      - name: Upload release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'cem-tool-${{ github.ref_name }}.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}